### ISSUE TITLE
Retries are not delayed

### ISSUE THREAD

**Issue by oliversalzburg** [voxpelli/node-pg-pubsub#10]
I don't know if this is an issue with pg-pubsub or promised-retry, but there are never any delays between (re)connection attempts.

```
2016-06-30 11:51:36.109 [DEBUG ] (                 postgres) error: too many connections for database "db"
2016-06-30 11:51:36.109                                          at Connection.parseE (C:\prj\node_modules\pg\lib\connection.js:539:11)
2016-06-30 11:51:36.109                                          at Connection.parseMessage (C:\prj\node_modules\pg\lib\connection.js:366:17)
2016-06-30 11:51:36.109                                          at Socket.<anonymous> (C:\prj\node_modules\pg\lib\connection.js:105:22)
2016-06-30 11:51:36.109                                          at emitOne (events.js:77:13)
2016-06-30 11:51:36.109                                          at Socket.emit (events.js:169:7)
2016-06-30 11:51:36.109                                          at readableAddChunk (_stream_readable.js:153:18)
2016-06-30 11:51:36.109                                          at Socket.Readable.push (_stream_readable.js:111:10)
2016-06-30 11:51:36.109                                          at TCP.onread (net.js:531:20)
2016-06-30 11:51:36.110 [DEBUG ] (                 postgres) Retry 1: Waiting 278 ms to try pubsub again
2016-06-30 11:51:36.112 [DEBUG ] (                 postgres) Error: read ECONNRESET
2016-06-30 11:51:36.112                                          at exports._errnoException (util.js:870:11)
2016-06-30 11:51:36.112                                          at TCP.onread (net.js:552:26)
2016-06-30 11:51:36.112 [DEBUG ] (                 postgres) Retry 1: Waiting 605 ms to try pubsub again
2016-06-30 11:51:36.330 [DEBUG ] (                 postgres) error: database "db" does not exist
2016-06-30 11:51:36.330                                          at Connection.parseE (C:\prj\node_modules\pg\lib\connection.js:539:11)
2016-06-30 11:51:36.330                                          at Connection.parseMessage (C:\prj\node_modules\pg\lib\connection.js:366:17)
2016-06-30 11:51:36.330                                          at Socket.<anonymous> (C:\prj\node_modules\pg\lib\connection.js:105:22)
2016-06-30 11:51:36.330                                          at emitOne (events.js:77:13)
2016-06-30 11:51:36.330                                          at Socket.emit (events.js:169:7)
2016-06-30 11:51:36.330                                          at readableAddChunk (_stream_readable.js:153:18)
2016-06-30 11:51:36.330                                          at Socket.Readable.push (_stream_readable.js:111:10)
2016-06-30 11:51:36.330                                          at TCP.onread (net.js:531:20)
2016-06-30 11:51:36.331 [DEBUG ] (                 postgres) Retry 2: Waiting 176 ms to try pubsub again
2016-06-30 11:51:36.351 [DEBUG ] (                 postgres) error: database "db" does not exist
2016-06-30 11:51:36.351                                          at Connection.parseE (C:\prj\node_modules\pg\lib\connection.js:539:11)
2016-06-30 11:51:36.351                                          at Connection.parseMessage (C:\prj\node_modules\pg\lib\connection.js:366:17)
2016-06-30 11:51:36.351                                          at Socket.<anonymous> (C:\prj\node_modules\pg\lib\connection.js:105:22)
2016-06-30 11:51:36.351                                          at emitOne (events.js:77:13)
2016-06-30 11:51:36.351                                          at Socket.emit (events.js:169:7)
2016-06-30 11:51:36.351                                          at readableAddChunk (_stream_readable.js:153:18)
2016-06-30 11:51:36.351                                          at Socket.Readable.push (_stream_readable.js:111:10)
2016-06-30 11:51:36.351                                          at TCP.onread (net.js:531:20)
2016-06-30 11:51:36.351 [DEBUG ] (                 postgres) Retry 1: Waiting 923 ms to try pubsub again
2016-06-30 11:51:36.371 [DEBUG ] (                 postgres) error: database "db" does not exist
2016-06-30 11:51:36.371                                          at Connection.parseE (C:\prj\node_modules\pg\lib\connection.js:539:11)
2016-06-30 11:51:36.371                                          at Connection.parseMessage (C:\prj\node_modules\pg\lib\connection.js:366:17)
2016-06-30 11:51:36.371                                          at Socket.<anonymous> (C:\prj\node_modules\pg\lib\connection.js:105:22)
2016-06-30 11:51:36.371                                          at emitOne (events.js:77:13)
2016-06-30 11:51:36.371                                          at Socket.emit (events.js:169:7)
2016-06-30 11:51:36.371                                          at readableAddChunk (_stream_readable.js:153:18)
2016-06-30 11:51:36.371                                          at Socket.Readable.push (_stream_readable.js:111:10)
2016-06-30 11:51:36.371                                          at TCP.onread (net.js:531:20)
```

It's also notable that the retry counter is off.

**Comment by oliversalzburg** [comment]
Removing the [reset](https://github.com/voxpelli/node-pg-pubsub/blob/master/index.js#L30) gives me results a lot closer to what I would expect.

**Comment by voxpelli** [comment]
Yeah, that doesn't look right at all. Thanks for reporting!

**Comment by oliversalzburg** [comment]
@voxpelli Any chance of getting this fixed? Would you accept a PR that removes the reset I mentioned?

**Comment by voxpelli** [comment]
@oliversalzburg Looking closer at the code it do look like the `.reset()` is needed to reset the `promisedResult` and ensure that a new connection is obtained: https://github.com/voxpelli/node-promised-retry/blob/master/index.js#L144

I do agree that the failure count shouldn't be reset, so perhaps a bool argument on the `reset()` that tells whether the reset should reset the failure count or not would be the proper solution.

Else if your database were to go away after a successful connection had been obtained then it would be impossible to ever obtain a successful one after it's up again.

Sorry for not taking a look at this earlier. I'll happily accept PR:s, else I try to find time to fix this asap.

**Comment by oliversalzburg** [comment]
Okay, that makes sense. But it also makes me doubt a bit if I understand the code enough to properly fix it ;D
